name 'appserv_kanboard_cb'
maintainer 'Kanboard Project Team'
maintainer_email 'infra@example.com'
license 'All Rights Reserved'
description 'Installs and configures a Kanboard application server'
version '0.2.0'
chef_version '>= 16.0'

issues_url 'https://example.com/kanboardproject/issues'
source_url 'https://example.com/kanboardproject/repo'